
'use client';

import React, { createContext, useContext, useState, ReactNode, useCallback, useMemo, useEffect, useRef } from 'react';
import { translateText } from '@/ai/flows/translate-text';
import { useToast } from '@/hooks/use-toast';

// Define all original English strings here.
const originalTexts: { [key: string]: string } = {
  // Site Header
  'Notifications': 'Notifications',
  'No new notifications': 'No new notifications',
  'Profile': 'Profile',
  'Logout': 'Logout',
  'Login': 'Login',

  // Site Sidebar
  'Dashboard': 'Dashboard',
  'Marketplace': 'Marketplace',
  'My Listings': 'My Listings',
  'Orders': 'Orders',
  'Sales History': 'Sales History',
  'Messages': 'Messages',
  'My Purchases': 'My Purchases',
  'My Bookmarks': 'My Bookmarks',
  'Create Listing': 'Create Listing',
  'AgroGuru AI': 'AgroGuru AI',
  'Daily Reports': 'Daily Reports',

  // Marketplace Page
  'Explore the Market': 'Explore the Market',
  'Find fresh produce directly from local farmers across the region.': 'Find fresh produce directly from local farmers across the region.',
  'Filters': 'Filters',
  'Category': 'Category',
  'All Categories': 'All Categories',
  'Fruits': 'Fruits',
  'Vegetables': 'Vegetables',
  'Grains': 'Grains',
  'Location': 'Location',
  'All Locations': 'All Locations',
  'Sindh': 'Sindh',
  'Punjab': 'Punjab',
  'Balochistan': 'Balochistan',
  'Khyber Pakhtunkhwa': 'Khyber Pakhtunkhwa',
  'Gilgit-Baltistan': 'Gilgit-Baltistan',
  'Azad Jammu & Kashmir': 'Azad Jammu & Kashmir',
  'Islamabad Capital Territory': 'Islamabad Capital Territory',
  'Min price': 'Min price',
  'Max price': 'Max price',
  'Apply': 'Apply',
  'Clear': 'Clear',
  'No listings found': 'No listings found',
  'There are currently no produce listings available. Please check back later.': 'There are currently no produce listings available. Please check back later.',
  'Try adjusting your filters or check back later.': 'Try adjusting your filters or check back later.',
  'Search for produce...': 'Search for produce...',


  // Product Card
  'Contact': 'Contact',
  'reviews': 'reviews',
  'Buy Now': 'Buy Now',
  
  // Dashboard
  'Buyer Dashboard': 'Buyer Dashboard',
  'Find deals, manage orders, and connect with sellers.': 'Find deals, manage orders, and connect with sellers.',
  'Find Produce': 'Find Produce',
  'Search for \'Onion from Sindh under 100/kg\'...': 'Search for \'Onion from Sindh under 100/kg\'...',
  'Search': 'Search',
  'Recent Purchases': 'Recent Purchases',
  'View all': 'View all',
  'A quick look at your recent orders.': 'A quick look at your recent orders.',
  'Saved Sellers': 'Saved Sellers',
  'Your favorite farmers and suppliers.': 'Your favorite farmers and suppliers.',
  'View Profile': 'View Profile',
  'Active Offers & Requests': 'Active Offers & Requests',
  'Track your ongoing negotiations and order requests.': 'Track your ongoing negotiations and order requests.',
  'View Chat': 'View Chat',
  'Sales Dashboard': 'Sales Dashboard',
  'Here\'s an overview of your performance on SmartBazaar.': 'Here\'s an overview of your performance on SmartBazaar.',
  'Buyer Matches / Requests': 'Buyer Matches / Requests',
  'Potential buyers interested in your types of crops.': 'Potential buyers interested in your types of crops.',
  'Total Revenue': 'Total Revenue',
  'Total Sales': 'Total Sales',
  'Top Buyer': 'Top Buyer',
  'Top Performing Crop': 'Top Performing Crop',
  'Latest Market Prices': 'Latest Market Prices',
  'Sales Trends': 'Sales Trends',
  'Your sales revenue over the last 6 months.': 'Your sales revenue over the last 6 months.',
  'Crop Performance': 'Crop Performance',
  'Revenue generated by your top crops.': 'Revenue generated by your top crops.',
  'Incoming Orders': 'Incoming Orders',
  'Manage Orders': 'Manage Orders',
  
  // My Bookmarks
  'Your saved listings for future reference.': 'Your saved listings for future reference.',
  'You haven\'t bookmarked any items yet.': 'You haven\'t bookmarked any items yet.',
  'Click the star icon on a listing to save it here.': 'Click the star icon on a listing to save it here.',
  'Explore Marketplace': 'Explore Marketplace',

  // My Purchases
  'Review your order history and track deliveries.': 'Review your order history and track deliveries.',
  'Product': 'Product',
  'Sold By': 'Sold By',
  'Status': 'Status',
  'You haven\'t made any purchases yet.': 'You haven\'t made any purchases yet.',
  'When you do, they will appear here.': 'When you do, they will appear here.',
  'Actions': 'Actions',
  'View Details': 'View Details',
  'Order Details': 'Order Details',
  'Order Summary': 'Order Summary',

  // Profile Page
  'Not specified': 'Not specified',
  'A dedicated member of the SmartBazaar community, connecting farmers and buyers for fresh, quality produce.': 'A dedicated member of the SmartBazaar community, connecting farmers and buyers for fresh, quality produce.',
  'Edit Profile': 'Edit Profile',
  'Member since': 'Member since',
  'My Active Listings': 'My Active Listings',
  'Manage your current produce listings.': 'Manage your current produce listings.',
  'New Listing': 'New Listing',
  'No active listings': 'No active listings',
  'Get started by creating your first listing.': 'Get started by creating your first listing.',
  'My Purchase History': 'My Purchase History',
  'View your past produce orders.': 'View your past produce orders.',
  'No purchases yet': 'No purchases yet',
  'Explore the marketplace and make your first purchase.': 'Explore the marketplace and make your first purchase.',
  'Start Shopping': 'Start Shopping',

  // Sell Page
  'Create a New Listing': 'Create a New Listing',
  'Fill out the details below to sell your produce on SmartBazaar.': 'Fill out the details below to sell your produce on SmartBazaar.',
  'Product Image': 'Product Image',
  'Click to upload or drag & drop': 'Click to upload or drag & drop',
  'PNG, JPG up to 5MB': 'PNG, JPG up to 5MB',
  'Identifying crop...': 'Identifying crop...',
  'Crop Name': 'Crop Name',
  'Select a category': 'Select a category',
  'Other': 'Other',
  'Quantity': 'Quantity',
  'Unit': 'Unit',
  'Select a unit': 'Select a unit',
  'Kilogram (kg)': 'Kilogram (kg)',
  'Maund (mound)': 'Maund (mound)',
  'Dozen': 'Dozen',
  'Piece': 'Piece',
  'Price per Unit (PKR)': 'Price per Unit (PKR)',
  'Suggest Price': 'Suggest Price',
  'AI Price Suggestion': 'AI Price Suggestion',
  'Latest market price:': 'Latest market price:',
  'per unit.': 'per unit.',
  'Location / City': 'Location / City',
  'Description (Optional)': 'Description (Optional)',
  'Add details about your produce, e.g., \'Organically grown, ready for harvest\'.': 'Add details about your produce, e.g., \'Organically grown, ready for harvest\'.',
  'This will help buyers know more about your product.': 'This will help buyers know more about your product.',
  'Proceed to Pricing': 'Proceed to Pricing',
  'Back to Details': 'Back to Details',
  'Step 1: Produce Details': 'Step 1: Produce Details',
  'Step 2: Set Your Price': 'Step 2: Set Your Price',

  // Auth Pages
  'Welcome Back': 'Welcome Back',
  'Enter your credentials to access your account.': 'Enter your credentials to access your account.',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot your password?': 'Forgot your password?',
  'Login with Google': 'Login with Google',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Sign up': 'Sign up',
  'Join SmartBazaar': 'Join SmartBazaar',
  'Choose your role and start connecting': 'Choose your role and start connecting',
  'Farmer': 'Farmer',
  'Buyer': 'Buyer',
  'First name': 'First name',
  'Last name': 'Last name',
  'CNIC Number': 'CNIC Number',
  'Phone Number': 'Phone Number',
  'Create a farmer account': 'Create a farmer account',
  'Create a buyer account': 'Create a buyer account',
  'Already have an account?': 'Already have an account?',
  'Log in': 'Log in',
  'Detect My Location': 'Detect My Location',
  'Detecting...': 'Detecting...',
  'Address': 'Address',
  'City': 'City',
  'Province': 'Province',
  'Select a Province': 'Select a Province',

  // Chat Page
    'No conversations yet.': 'No conversations yet.',
    'Select a conversation to start chatting.': 'Select a conversation to start chatting.',
    'Loading chats...': 'Loading chats...',
    'Creating chat...': 'Creating chat...',
    'Type your message...': 'Type your message...',
    'Send message': 'Send message',
    
  // Orders page
    'Review, accept, and track all your orders.': 'Review, accept, and track all your orders.',
    'Pending Approval': 'Pending Approval',
    'All Orders': 'All Orders',
    'Total': 'Total',
    'Date': 'Date',
    'No pending orders right now.': 'No pending orders right now.',
    'No orders found.': 'No orders found.',
    'Accept': 'Accept',
    'Reject': 'Reject',
    'Update Status': 'Update Status',
    'pending': 'Pending',
    'accepted': 'Accepted',
    'rejected': 'Rejected',
    'dispatched': 'Dispatched',
    'in_warehouse': 'In Warehouse',
    'out_for_delivery': 'Out for Delivery',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',

    // Reports Page
    'Your Daily Farming Reports': 'Your Daily Farming Reports',
    'AI-generated insights based on your farm and local weather.': 'AI-generated insights based on your farm and local weather.',
    'Generate Today\'s Report': 'Generate Today\'s Report',
    'Generating...': 'Generating...',
    'No reports found.': 'No reports found.',
    'Generate your first report to get daily advice.': 'Generate your first report to get daily advice.',
    'Report for': 'Report for',

};

type OriginalTextKeys = keyof typeof originalTexts;

type TranslationCache = {
  [language: string]: { [key: string]: string };
};

interface LanguageContextType {
  currentLanguage: string;
  isTranslating: boolean;
  setLanguage: (language: string) => Promise<void>;
  t: (key: OriginalTextKeys) => string;
  manageTranslations: (keys: OriginalTextKeys[]) => (key: OriginalTextKeys) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState('English');
  const [translations, setTranslations] = useState<{ [key: string]: string }>(originalTexts);
  const [translationCache, setTranslationCache] = useState<TranslationCache>({ 'English': originalTexts });
  const [isTranslating, setIsTranslating] = useState(false);
  const { toast } = useToast();
  
  const setLanguage = useCallback(async (language: string) => {
    if (language === currentLanguage) return;
    
    setIsTranslating(true);
    setCurrentLanguage(language);

    if (language === 'English') {
        setTranslations(originalTexts);
        setIsTranslating(false);
        return;
    }
    
    // If we have a full cache for this language, use it.
    // Otherwise, `manageTranslations` will fetch what's needed.
    if (translationCache[language]) {
      setTranslations(translationCache[language]);
    } else {
      // Temporarily revert to English while new translations are fetched by components
      setTranslations(originalTexts);
    }
    setIsTranslating(false); // Let components handle their own loading state
  }, [currentLanguage, translationCache]);

  const translateBatch = useCallback(async (keysToTranslate: OriginalTextKeys[], targetLanguage: string) => {
    if (targetLanguage === 'English' || keysToTranslate.length === 0) return;

    // Filter out keys that are already in the cache for the target language
    const keysToActuallyFetch = keysToTranslate.filter(key => 
        !translationCache[targetLanguage] || !translationCache[targetLanguage][key]
    );

    if (keysToActuallyFetch.length === 0) return;

    const textsToTranslate = keysToActuallyFetch.reduce((acc, key) => {
      acc[key] = originalTexts[key];
      return acc;
    }, {} as { [key: string]: string });
    
    setIsTranslating(true);
    try {
      const result = await translateText({
        texts: textsToTranslate,
        targetLanguage: targetLanguage,
      });

      if (result && result.translations) {
        const newTranslations = result.translations.reduce((acc, item) => {
          acc[item.key as OriginalTextKeys] = item.translatedText;
          return acc;
        }, {} as { [key: string]: string });
        
        // Update the main cache
        setTranslationCache(prevCache => {
            const updatedLanguageCache = { ...(prevCache[targetLanguage] || {}), ...newTranslations };
            return { ...prevCache, [targetLanguage]: updatedLanguageCache };
        });

        // If the current language is the one we just translated for, update the active translations
        if (targetLanguage === currentLanguage) {
             setTranslations(prev => ({ ...prev, ...newTranslations }));
        }
      }

    } catch (error) {
      console.error('Translation failed:', error);
      toast({
        variant: 'destructive',
        title: 'Translation Failed',
        description: `Could not translate some text to ${targetLanguage}.`,
      });
    } finally {
      setIsTranslating(false);
    }
  }, [toast, currentLanguage, translationCache]);


  const t = (key: OriginalTextKeys): string => {
    return translations[key] || originalTexts[key] || key;
  };
  
  const manageTranslations = (keys: OriginalTextKeys[]) => {
    // Effect to trigger translation when language changes
    useEffect(() => {
        if (currentLanguage !== 'English') {
            translateBatch(keys, currentLanguage);
        } else {
            // When switching back to English, reset translations immediately
            setTranslations(originalTexts);
        }
    }, [currentLanguage, keys]);

    // Return a translation function `t` that is aware of the component's keys
    return (key: OriginalTextKeys): string => {
        // Use the cached translation for the current language if available
        const langCache = translationCache[currentLanguage];
        if (langCache && langCache[key]) {
            return langCache[key];
        }
        // Fallback to English
        return originalTexts[key] || key;
    };
  };

  const value = useMemo(() => ({
     currentLanguage, isTranslating, setLanguage, t, manageTranslations
  }), [currentLanguage, isTranslating, setLanguage, t, manageTranslations]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
