
"use client"

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { ChartContainer, ChartTooltipContent } from "@/components/ui/chart"
import { DollarSign, ShoppingBag, Users, TrendingUp, UserCheck, Star, Search, LandPlot, PackageCheck, PackageX, Truck, ListOrdered } from "lucide-react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { useUser } from "@/firebase/auth/use-user"
import { Input } from "@/components/ui/input"
import { ProductCard } from "@/components/product-card"
import type { Listing, ListingDocument, UserDocument, Order, OrderDocument, OrderStatus } from "@/lib/types"
import { useLanguage } from "@/context/language-context"
import { useFirebase } from "@/firebase"
import { useState, useEffect, useMemo } from "react"
import { collection, query, where, onSnapshot, getDoc, doc, getDocs, orderBy, limit, updateDoc } from "firebase/firestore"
import { Skeleton } from "@/components/ui/skeleton"
import { errorEmitter } from "@/firebase/error-emitter"
import { FirestorePermissionError } from "@/firebase/errors"
import { Separator } from "@/components/ui/separator"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { cn } from '@/lib/utils';
import { useToast } from "@/hooks/use-toast"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"

type MarketPrice = {
    id: string;
    crop: string;
    province: string;
    price: number;
    unit: string;
    date: string;
}

type GroupedMarketPrices = {
    [cropName: string]: MarketPrice[];
}

const statusStyles: { [key: string]: string } = {
    pending: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    accepted: 'bg-blue-100 text-blue-800 border-blue-300',
    dispatched: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    in_warehouse: 'bg-purple-100 text-purple-800 border-purple-300',
    out_for_delivery: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    delivered: 'bg-green-100 text-green-800 border-green-300',
    rejected: 'bg-red-100 text-red-800 border-red-300',
    cancelled: 'bg-gray-100 text-gray-800 border-gray-300',
}


const chartConfig = {
  sales: { label: "Sales (PKR)", color: "hsl(var(--primary))" },
  revenue: { label: "Revenue (PKR)", color: "hsl(var(--primary))" },
  price: { label: "Price (PKR)", color: "hsl(var(--primary))" },
}

const farmerTranslationKeys = [
    'Sales Dashboard',
    'Here\'s an overview of your performance on SmartBazaar.',
    'Buyer Matches / Requests',
    'Potential buyers interested in your types of crops.',
    'Contact',
    'Total Revenue',
    'Total Sales',
    'Top Buyer',
    'Top Performing Crop',
    'Latest Market Prices',
    'Sales Trends',
    'Your sales revenue over the last 6 months.',
    'Crop Performance',
    'Revenue generated by your top crops.',
    'Incoming Orders',
    'Manage Orders'
];

function FarmerDashboard() {
  const { user, data: userData } = useUser();
  const { db } = useFirebase();
  const t = useLanguage().manageTranslations(farmerTranslationKeys);
  const { toast } = useToast();
  const [salesData, setSalesData] = useState<any[]>([]);
  const [cropPerformanceData, setCropPerformanceData] = useState<any[]>([]);
  const [stats, setStats] = useState({ totalRevenue: 0, totalSales: 0, pendingOrders: 0 });
  const [topBuyer, setTopBuyer] = useState<{ name: string; orders: number } | null>(null);
  const [marketPrices, setMarketPrices] = useState<MarketPrice[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isMarketPricesLoading, setIsMarketPricesLoading] = useState(true);

  useEffect(() => {
    if (!user || !db) return;

    const ordersRef = collection(db, 'orders');
    const q = query(ordersRef, where('farmerId', '==', user.uid), where('status', '==', 'pending'));

    const unsubscribe = onSnapshot(q, (snapshot) => {
        setStats(prev => ({...prev, pendingOrders: snapshot.size}));
    }, (error) => {
        errorEmitter.emit('permission-error', new FirestorePermissionError({ path: ordersRef.path, operation: 'list' }));
    });

    return () => unsubscribe();
  }, [user, db]);


  useEffect(() => {
    if (!db) {
        setIsMarketPricesLoading(false);
        return;
    }

    setIsMarketPricesLoading(true);
    const today = new Date().toISOString().split('T')[0]; // Get date in YYYY-MM-DD format
    const marketPricesColRef = collection(db, 'market_prices');
    const q = query(marketPricesColRef, where("date", "==", today));
    
    const unsubscribe = onSnapshot(q, (snapshot) => {
        const todaysPrices = snapshot.docs.map(doc => {
          const data = doc.data();
          return {
              id: doc.id,
              crop: data.crop,
              province: data.province,
              price: data.average,
              unit: data.unit,
              date: data.date,
          };
        });
        setMarketPrices(todaysPrices);
        setIsMarketPricesLoading(false);
    }, (error) => {
        const permissionError = new FirestorePermissionError({
            path: 'market_prices',
            operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setMarketPrices([]);
        setIsMarketPricesLoading(false);
    });

    return () => unsubscribe();
  }, [db]);


  useEffect(() => {
    if (!user || !db) {
        setIsLoading(false);
        return;
    }

    setIsLoading(true);
    const q = query(collection(db, "orders"), where("farmerId", "==", user.uid), where("status", "==", "delivered"));
    
    const unsubscribe = onSnapshot(q, async (snapshot) => {
        if (snapshot.empty) {
            setStats(prev => ({ ...prev, totalRevenue: 0, totalSales: 0 }));
            setSalesData([]);
            setCropPerformanceData([]);
            setTopBuyer(null);
            setIsLoading(false);
            return;
        }

        let totalRevenue = 0;
        const salesByMonth: { [key: string]: number } = {};
        const revenueByCrop: { [key: string]: { revenue: number, sales: number } } = {};
        const ordersByBuyer: { [key: string]: { name: string, orders: number } } = {};

        snapshot.docs.forEach(doc => {
            const order = doc.data() as OrderDocument;
            totalRevenue += order.farmerEarning;

            if (order.createdAt) {
                 const month = order.createdAt.toDate().toLocaleString('default', { month: 'short' });
                 salesByMonth[month] = (salesByMonth[month] || 0) + order.farmerEarning;
            }
            if (!revenueByCrop[order.cropName]) {
                revenueByCrop[order.cropName] = { revenue: 0, sales: 0 };
            }
            revenueByCrop[order.cropName].revenue += order.farmerEarning;
            revenueByCrop[order.cropName].sales += 1;

             if (!ordersByBuyer[order.buyerId]) {
                ordersByBuyer[order.buyerId] = { name: order.buyerInfo.name, orders: 0 };
            }
            ordersByBuyer[order.buyerId].orders += 1;
        });

        setStats(prev => ({ ...prev, totalRevenue, totalSales: snapshot.size }));
        setSalesData(Object.entries(salesByMonth).map(([month, sales]) => ({ month, sales })));
        setCropPerformanceData(Object.entries(revenueByCrop).map(([crop, data]) => ({ crop, revenue: data.revenue })).sort((a, b) => b.revenue - a.revenue));

        // Find top buyer
        if (Object.keys(ordersByBuyer).length > 0) {
            const topBuyerEntry = Object.values(ordersByBuyer).sort((a, b) => b.orders - a.orders)[0];
            setTopBuyer(topBuyerEntry);
        }
        setIsLoading(false);
    }, (error) => {
        const permissionError = new FirestorePermissionError({
            path: 'orders',
            operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setIsLoading(false);
    });

    return () => unsubscribe();
}, [user, db]);

  const groupedPrices = useMemo(() => {
    return marketPrices.reduce((acc, price) => {
        (acc[price.crop] = acc[price.crop] || []).push(price);
        return acc;
    }, {} as GroupedMarketPrices);
  }, [marketPrices]);

  const topPerformingCrop = cropPerformanceData.length > 0 ? cropPerformanceData[0] : null;


  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl lg:text-4xl font-bold tracking-tight font-headline">{t('Sales Dashboard')}</h1>
        <p className="text-muted-foreground mt-2">{t('Here\'s an overview of your performance on SmartBazaar.')}</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{t('Total Revenue')}</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            {isLoading ? <Skeleton className="h-8 w-32"/> : <div className="text-2xl font-bold">PKR {stats.totalRevenue.toLocaleString()}</div>}
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{t('Total Sales')}</CardTitle>
            <ShoppingBag className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
             {isLoading ? <Skeleton className="h-8 w-16"/> : <div className="text-2xl font-bold">+{stats.totalSales}</div>}
          </CardContent>
        </Card>
         <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{t('Incoming Orders')}</CardTitle>
            <ListOrdered className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            {isLoading ? <Skeleton className="h-8 w-16"/> : (
                 <>
                    <div className="text-2xl font-bold">{stats.pendingOrders}</div>
                     <p className="text-xs text-muted-foreground">requests waiting for approval</p>
                 </>
            )}
          </CardContent>
          <CardFooter>
            <Button size="sm" className="w-full" asChild>
                <Link href="/orders">
                    <PackageCheck className="mr-2 h-4 w-4"/>
                    {t('Manage Orders')}
                </Link>
            </Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{t('Top Performing Crop')}</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            {isLoading ? <Skeleton className="h-8 w-24"/> : topPerformingCrop ? (
                <>
                    <div className="text-2xl font-bold">{topPerformingCrop.crop}</div>
                    <p className="text-xs text-muted-foreground">PKR {topPerformingCrop.revenue.toLocaleString()} in revenue</p>
                </>
            ) : (
                 <div className="text-xl font-bold">N/A</div>
            )}
          </CardContent>
        </Card>
      </div>

      <div>
        <h2 className="text-2xl font-bold tracking-tight font-headline mb-4">{t('Latest Market Prices')}</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {isMarketPricesLoading ? (
            [...Array(3)].map((_, i) => (
                <Card key={i}>
                    <CardHeader className="p-4"><Skeleton className="h-6 w-32" /></CardHeader>
                    <CardContent className="p-4 pt-0 space-y-2">
                        <Skeleton className="h-8 w-24" />
                        <Skeleton className="h-4 w-full" />
                    </CardContent>
                </Card>
            ))
          ) : Object.keys(groupedPrices).length > 0 ? (
            Object.entries(groupedPrices).map(([cropName, prices]) => (
                 <Card key={cropName}>
                    <CardHeader className="p-4">
                      <CardTitle className="text-lg flex items-center gap-2">
                        <LandPlot className="h-5 w-5 text-primary" />
                        {cropName}
                      </CardTitle>
                       <CardDescription>As of {new Date(prices[0].date).toLocaleDateString()}</CardDescription>
                    </CardHeader>
                    <CardContent className="p-4 pt-0 space-y-3">
                        {prices.map((item) => (
                            <div key={item.id} className="flex justify-between items-center">
                                <div>
                                    <p className="font-medium">{item.province}</p>
                                    <p className="text-sm text-muted-foreground">PKR {item.price ? item.price.toLocaleString() : 'N/A'} / {item.unit}</p>
                                </div>
                            </div>
                        ))}
                    </CardContent>
                  </Card>
            ))
          ) : (
            <p className="text-muted-foreground col-span-3">No market price data available for today.</p>
          )}
        </div>
      </div>

      <div className="grid gap-8 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>{t('Sales Trends')}</CardTitle>
            <CardDescription>{t('Your sales revenue over the last 6 months.')}</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer config={chartConfig} className="h-[300px] w-full">
              <LineChart data={salesData} margin={{ top: 5, right: 20, left: -10, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="month" tickLine={false} axisLine={false} tickMargin={8} />
                <YAxis tickLine={false} axisLine={false} tickMargin={8} tickFormatter={(value) => `PKR ${value / 1000}k`} />
                <Tooltip cursor={false} content={<ChartTooltipContent />} />
                <Line type="monotone" dataKey="sales" stroke="var(--color-sales)" strokeWidth={2} dot={true} />
              </LineChart>
            </ChartContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>{t('Crop Performance')}</CardTitle>
            <CardDescription>{t('Revenue generated by your top crops.')}</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer config={chartConfig} className="h-[300px] w-full">
              <BarChart data={cropPerformanceData} layout="vertical" margin={{ top: 5, right: 20, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} />
                <YAxis type="category" dataKey="crop" tickLine={false} axisLine={false} tickMargin={8} width={80} />
                <XAxis type="number" hide />
                <Tooltip cursor={false} content={<ChartTooltipContent />} />
                <Bar dataKey="revenue" fill="var(--color-revenue)" radius={4} />
              </BarChart>
            </ChartContainer>
          </CardContent>
        </Card>
      </div>

    </div>
  )
}

const buyerTranslationKeys = [
    'Buyer Dashboard',
    'Find deals, manage orders, and connect with sellers.',
    'Find Produce',
    "Search for 'Onion from Sindh under 100/kg'...",
    'Recent Purchases',
    'View all',
    'A quick look at your recent orders.',
    'Saved Sellers',
    'Your favorite farmers and suppliers.',
    'View Profile',
    'Active Offers & Requests',
    'Track your ongoing negotiations and order requests.',
    'View Chat',
];

const BuyerDashboardLoadingSkeleton = () => {
    return (
        <div className="space-y-8">
            <div className="animate-pulse">
                <Skeleton className="h-12 w-96 mb-2" />
                <Skeleton className="h-4 w-1/2" />
            </div>
            <div className="grid gap-8 lg:grid-cols-2">
                <Card><CardHeader><Skeleton className="h-6 w-32" /></CardHeader><CardContent><Skeleton className="h-48 w-full" /></CardContent></Card>
                <Card><CardHeader><Skeleton className="h-6 w-32" /></CardHeader><CardContent><Skeleton className="h-48 w-full" /></CardContent></Card>
            </div>
            <Card><CardHeader><Skeleton className="h-6 w-48" /></CardHeader><CardContent><Skeleton className="h-24 w-full" /></CardContent></Card>
        </div>
    )
}


function BuyerDashboard() {
    const t = useLanguage().manageTranslations([...buyerTranslationKeys, 'Contact', 'Search']);
    const { db, user } = useFirebase();
    const [recentPurchases, setRecentPurchases] = useState<Listing[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        if (!db || !user) {
            setIsLoading(false);
            return;
        }

        setIsLoading(true);
        // Query for listings that this buyer has purchased.
        const q = query(
            collection(db, "listings"), 
            where("buyerId", "==", user.uid),
            where("status", "==", "sold"),
            orderBy("createdAt", "desc"),
            limit(2)
        );

        const unsubscribe = onSnapshot(q, async (snapshot) => {
            if (snapshot.empty) {
                setRecentPurchases([]);
                setIsLoading(false);
                return;
            }
            
            const listingsDataPromises = snapshot.docs.map(async (listingDoc) => {
                 const listingData = listingDoc.data() as ListingDocument;
                 const farmerDocRef = doc(db, 'users', listingData.farmerId);
                 const farmerDocSnap = await getDoc(farmerDocRef).catch(() => null);
                 const farmerData = farmerDocSnap?.data() as UserDocument | undefined;

                 return {
                    id: listingDoc.id,
                    farmer: {
                        uid: listingData.farmerId,
                        name: farmerData ? `${farmerData.firstName} ${farmerData.lastName}` : 'Unknown Farmer',
                        avatarUrl: farmerData?.photoURL || '',
                        rating: farmerData?.rating || 0,
                        reviews: farmerData?.reviews || 0,
                    },
                    crop: {
                        name: listingData.cropName,
                        imageUrl: listingData.imageUrl,
                        imageHint: listingData.imageHint,
                    },
                    quantity: listingData.quantity,
                    unit: listingData.unit,
                    pricePerUnit: listingData.pricePerUnit,
                    location: listingData.location,
                    description: listingData.description,
                    createdAt: listingData.createdAt.toDate(),
                    status: listingData.status,
                 };
            });
            const listingsData = await Promise.all(listingsDataPromises);
            setRecentPurchases(listingsData);
            setIsLoading(false);
        }, (error) => {
             errorEmitter.emit('permission-error', new FirestorePermissionError({
                path: 'listings',
                operation: 'list',
            }));
            setIsLoading(false);
        });
        return () => unsubscribe();
    }, [db, user]);

    if (isLoading) {
        return <BuyerDashboardLoadingSkeleton />;
    }

    return (
        <div className="space-y-8">
            <div>
                <h1 className="text-3xl lg:text-4xl font-bold tracking-tight font-headline">{t('Buyer Dashboard')}</h1>
                <p className="text-muted-foreground mt-2">{t('Find deals, manage orders, and connect with sellers.')}</p>
            </div>

            <div className="grid gap-8 lg:grid-cols-2">
                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center justify-between">
                            <span>{t('Recent Purchases')}</span>
                            <Link href="/my-purchases" className="text-sm font-medium text-primary hover:underline">{t('View all')}</Link>
                        </CardTitle>
                        <CardDescription>{t('A quick look at your recent orders.')}</CardDescription>
                    </CardHeader>
                    <CardContent>
                        {recentPurchases.length > 0 ? (
                             <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                {recentPurchases.map(listing => (
                                    <ProductCard key={listing.id} listing={listing} />
                                ))}
                            </div>
                        ) : (
                            <p className="text-muted-foreground">No recent purchases.</p>
                        )}
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader>
                        <CardTitle>{t('Saved Sellers')}</CardTitle>
                        <CardDescription>{t('Your favorite farmers and suppliers.')}</CardDescription>
                    </CardHeader>
                    <CardContent>
                         <p className="text-muted-foreground">Feature coming soon.</p>
                    </CardContent>
                </Card>
            </div>
            
             <Card>
                <CardHeader>
                    <CardTitle>{t('Active Offers & Requests')}</CardTitle>
                    <CardDescription>{t('Track your ongoing negotiations and order requests.')}</CardDescription>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">Feature coming soon.</p>
                </CardContent>
            </Card>
        </div>
    );
}

export default function DashboardPage() {
    const { data: userData, isLoading: isUserLoading } = useUser();
    const userRole = userData?.role;

    if (isUserLoading) {
        return userRole === 'farmer' ? (
             <div className="space-y-8 animate-pulse">
                <div className="space-y-2">
                    <Skeleton className="h-10 w-1/2" />
                    <Skeleton className="h-4 w-3/4" />
                </div>
                <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                    <Skeleton className="h-36 w-full" />
                    <Skeleton className="h-36 w-full" />
                    <Skeleton className="h-36 w-full" />
                    <Skeleton className="h-36 w-full" />
                </div>
                 <div className="grid gap-8 lg:grid-cols-2">
                    <Skeleton className="h-80 w-full" />
                    <Skeleton className="h-80 w-full" />
                </div>
             </div>
        ) : <BuyerDashboardLoadingSkeleton />;
    }

    if (userRole === 'farmer') {
        return <FarmerDashboard />;
    }
    
    return <BuyerDashboard />;
}

    